# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64ab7973f9d244411f631876829b23fdcd1b5eecced4ed29dab45baa21f3fe2eb17ae42b06954dd5eca48466ae566deaf7c439ff0d06099ddd1641660f32455c

test:
  secret_key_base: 89c58c5dac1164d738d5dca7dcdeb1dfcbde4b10b6a6764e3088171c2c8487b1962b7e4ac0d12550d8fe861390ee915ff15ec511d94470d2a276905d5c3dfe13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
